url: 'https://www.mikeyslice.com'
permalink: '/:title/'
markdown: kramdown
exclude:
  - .c9
pagination:
  per_page: '9'
title: Mikeyslice.com - Home
description: >-
  Official website of Mikeyslice, Twitch Streamer and Content Creator on
  YouTube.
header-title: Twitch Streamer and Content Creator on YouTube
per-page: '10'
