url: 'https://www.mikeyslice.com'
permalink: '/:title/'
markdown: kramdown
exclude:
  - .c9
plugins:
  - jekyll-redirect-from
  - jekyll-paginate-v2
pagination:
  category: posts
  collection: posts
  debug: false
  enabled: true
  limit: 0
  per_page: '5'
  permalink: '/:num/'
  sort_field: date
  sort_reverse: true
  title: ':title - page :num'
  trail:
    after: 0
    before: 0
title: Mikeyslice.com - Home
description: >-
  Official website of Mikeyslice, Twitch Streamer and Content Creator on
  YouTube.
