url: 'https://www.mikeyslice.com'
permalink: '/:title/'
# C9 configuration 
port: 8080
host: 0.0.0.0
baseurl: ''
markdown: kramdown
exclude:
  - .c9
plugins:
  - jekyll-redirect-from
  - jekyll-paginate-v2
pagination:
  category: posts
  collection: posts
  debug: false
  enabled: true
  limit: 0
  per_page: '10'
  permalink: '/:num/'
  sort_field: date
  sort_reverse: true
  title: ':title - page :num'
title: MikeySlice - Home
description: >-
  Official website of MikeySlice, Twitch Streamer and Content Creator on
  YouTube.
header-title: "Enhance your Skillz, and boost your income!"

